steps:
  # 1. Build Docker image untuk backend
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", ".env"]
    dir: "backend"

  # 2. Build Docker image dari folder backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/notes-143-be", "."]
    dir: "backend"

  # 3. Push image ke Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/notes-143-be"]

  # 3. Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "notes-143-be",
        "--image",
        "gcr.io/$PROJECT_ID/notes-143-be",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--add-cloudsql-instances",
        "mimetic-sweep-450606-j0:us-central1:tcc",   
        "--set-env-vars",
        "CLOUD_SQL_CONNECTION_NAME=mimetic-sweep-450606-j0:us-central1:tcc,DB_USER=root,DB_PASSWORD=,DB_NAME=webnotes"
      ]

# Log hanya akan disimpan di Google Cloud Logging
# Log tidak akan disimpan di Google Cloud Storage (butuh hak akses).
options:
  logging: CLOUD_LOGGING_ONLY
